services:
  - type: web
    name: todoapp
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: todoapp-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: todoapp-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: todoapp-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect

databases:
  - name: todoapp-db
    plan: free
    databaseName: todoapp_db
    user: postgres
