name: CI/CD Pipeline — TodoApp DevOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: mirajohenry/todoapp

jobs:

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build et Test
        run: mvn clean package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar

  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Succes
        run: echo "Image publiee sur Docker Hub avec succes !"

  notify:
    name: Resume Pipeline
    runs-on: ubuntu-latest
    needs: [build-and-test, docker-build-push]
    if: always()

    steps:
      - name: Resume
        run: |
          echo "=================================="
          echo "  PIPELINE TODOAPP DEVOPS"
          echo "=================================="
          echo "  Branch  : ${{ github.ref_name }}"
          echo "  Commit  : ${{ github.sha }}"
          echo "  Auteur  : ${{ github.actor }}"
          echo "  Build   : ${{ needs.build-and-test.result }}"
          echo "  Docker  : ${{ needs.docker-build-push.result }}"
          echo "=================================="
